use super::consts::*;

#[repr(u32)]
#[derive(Debug, Copy, Clone)]
pub enum KeyboardKey {
    Reserved = KEY_RESERVED,

    Esc = KEY_ESC,
    F1 = KEY_F1,
    F2 = KEY_F2,
    F3 = KEY_F3,
    F4 = KEY_F4,
    F5 = KEY_F5,
    F6 = KEY_F6,
    F7 = KEY_F7,
    F8 = KEY_F8,
    F9 = KEY_F9,
    F10 = KEY_F10,
    F11 = KEY_F11,
    F12 = KEY_F12,

    Insert = KEY_INSERT,
    Delete = KEY_DELETE,
    Home = KEY_HOME,
    End = KEY_END,
    PgUp = KEY_PAGEUP,
    PgDn = KEY_PAGEDOWN,

    Minus = KEY_MINUS,
    Equal = KEY_EQUAL,

    LeftBrace = KEY_LEFTBRACE,
    RightBrace = KEY_RIGHTBRACE,
    Semicolon = KEY_SEMICOLON,
    Apostrophe = KEY_APOSTROPHE,
    Grave = KEY_GRAVE,
    BackSlash = KEY_BACKSLASH,

    Comma = KEY_COMMA,
    Dot = KEY_DOT,
    Slash = KEY_SLASH,
    KPasteRisk = KEY_KPASTERISK,

    ScrollDown = KEY_SCROLLDOWN,
    ScrollUp = KEY_SCROLLUP,

    Kp0 = KEY_KP0,
    Kp1 = KEY_KP1,
    Kp2 = KEY_KP2,
    Kp3 = KEY_KP3,
    Kp4 = KEY_KP4,
    Kp5 = KEY_KP5,
    Kp6 = KEY_KP6,
    Kp7 = KEY_KP7,
    Kp8 = KEY_KP8,
    Kp9 = KEY_KP9,

    KpMinus = KEY_KPMINUS,
    KpPlus = KEY_KPPLUS,
    KpDot = KEY_KPDOT,
    KpEnter = KEY_KPENTER,
    KpSlash = KEY_KPSLASH,
    KpEqual = KEY_KPEQUAL,
    KpPlusMinus = KEY_KPPLUSMINUS,
    KpComma = KEY_KPCOMMA,
    Zenkakuhankaku = KEY_ZENKAKUHANKAKU,
    Key102ND = KEY_102ND,

    RO = KEY_RO,

    Katakana = KEY_KATAKANA,
    Hiragana = KEY_HIRAGANA,
    Henkan = KEY_HENKAN,
    KatakanaHiragana = KEY_KATAKANAHIRAGANA,
    Munekan = KEY_MUHENKAN,
    KpJpComma = KEY_KPJPCOMMA,
    Hanja = KEY_HANJA,
    Yen = KEY_YEN,

    SysRq = KEY_SYSRQ,
    LineFeed = KEY_LINEFEED,

    Macro = KEY_MACRO,
    Macro1 = KEY_MACRO1,
    Macro2 = KEY_MACRO2,
    Macro3 = KEY_MACRO3,
    Macro4 = KEY_MACRO4,
    Macro5 = KEY_MACRO5,
    Macro6 = KEY_MACRO6,
    Macro7 = KEY_MACRO7,
    Macro8 = KEY_MACRO8,
    Macro9 = KEY_MACRO9,
    Macro10 = KEY_MACRO10,
    Macro11 = KEY_MACRO11,
    Macro12 = KEY_MACRO12,
    Macro13 = KEY_MACRO13,
    Macro14 = KEY_MACRO14,
    Macro15 = KEY_MACRO15,
    Macro16 = KEY_MACRO16,
    Macro17 = KEY_MACRO17,
    Macro18 = KEY_MACRO18,
    Macro19 = KEY_MACRO19,
    Macro20 = KEY_MACRO20,
    Macro21 = KEY_MACRO21,
    Macro22 = KEY_MACRO22,
    Macro23 = KEY_MACRO23,
    Macro24 = KEY_MACRO24,
    Macro25 = KEY_MACRO25,
    Macro26 = KEY_MACRO26,
    Macro27 = KEY_MACRO27,
    Macro28 = KEY_MACRO28,
    Macro29 = KEY_MACRO29,
    Macro30 = KEY_MACRO30,

    MacroPresetCycle = KEY_MACRO_PRESET_CYCLE,
    MacroPreset1 = KEY_MACRO_PRESET1,
    MacroPreset2 = KEY_MACRO_PRESET2,
    MacroPreset3 = KEY_MACRO_PRESET3,

    Mute = KEY_MUTE,
    VolumeDown = KEY_VOLUMEDOWN,
    VolumeUp = KEY_VOLUMEUP,

    Power = KEY_POWER,
    Power2 = KEY_POWER2,

    Pause = KEY_PAUSE,
    Scale = KEY_SCALE,
    Stop = KEY_STOP,
    Again = KEY_AGAIN,
    Props = KEY_PROPS,
    Undo = KEY_UNDO,
    Front = KEY_FRONT,
    Copy = KEY_COPY,
    Open = KEY_OPEN,
    Paste = KEY_PASTE,
    Find = KEY_FIND,
    Cut = KEY_CUT,
    Help = KEY_HELP,
    Menu = KEY_MENU,
    Calc = KEY_CALC,
    Setup = KEY_SETUP,
    Sleep = KEY_SLEEP,
    WakeUp = KEY_WAKEUP,
    File = KEY_FILE,
    SendFile = KEY_SENDFILE,
    DeleteFile = KEY_DELETEFILE,
    XFer = KEY_XFER,

    Prog1 = KEY_PROG1,
    Prog2 = KEY_PROG2,
    Prog3 = KEY_PROG3,
    Prog4 = KEY_PROG4,
    Program = KEY_PROGRAM,

    WWW = KEY_WWW,
    MsDOS = KEY_MSDOS,
    Coffee = KEY_COFFEE,
    ScreenLock = KEY_SCROLLLOCK,
    Direction = KEY_DIRECTION,
    CycleWindows = KEY_CYCLEWINDOWS,
    Mail = KEY_MAIL,
    Bookmarks = KEY_BOOKMARKS,
    Computer = KEY_COMPUTER,

    Back = KEY_BACK,
    Forward = KEY_FORWARD,

    Compose = KEY_COMPOSE,

    Key0 = KEY_0,
    Key1 = KEY_1,
    Key2 = KEY_2,
    Key3 = KEY_3,
    Key4 = KEY_4,
    Key5 = KEY_5,
    Key6 = KEY_6,
    Key7 = KEY_7,
    Key8 = KEY_8,
    Key9 = KEY_9,

    BackSpace = KEY_BACKSPACE,
    NumLock = KEY_NUMLOCK,

    Tab = KEY_TAB,
    CapsLock = KEY_CAPSLOCK,

    RightShift = KEY_RIGHTSHIFT,
    RightCtrl = KEY_RIGHTCTRL,
    RightMeta = KEY_RIGHTMETA,
    RightAlt = KEY_RIGHTALT,

    LeftShift = KEY_LEFTSHIFT,
    LeftCtrl = KEY_LEFTCTRL,
    LeftMeta = KEY_LEFTMETA,
    LeftAlt = KEY_LEFTALT,

    Enter = KEY_ENTER,
    Space = KEY_SPACE,

    Up = KEY_UP,
    Down = KEY_DOWN,
    Left = KEY_LEFT,
    Right = KEY_RIGHT,

    Q = KEY_Q,
    W = KEY_W,
    E = KEY_E,
    R = KEY_R,
    T = KEY_T,
    Y = KEY_Y,
    U = KEY_U,
    I = KEY_I,
    O = KEY_O,
    P = KEY_P,
    A = KEY_A,
    S = KEY_S,
    D = KEY_D,
    F = KEY_F,
    G = KEY_G,
    H = KEY_H,
    J = KEY_J,
    K = KEY_K,
    L = KEY_L,
    Z = KEY_Z,
    X = KEY_X,
    C = KEY_C,
    V = KEY_V,
    B = KEY_B,
    N = KEY_N,
    M = KEY_M
}
