[package]
name = "qubicon_vulkan"
version = "0.0.0"
edition = "2021"

[features]
default = ["validation"]

windowing = []
validation = []

[dependencies]
ash = "0.37"
bitvec = "1.0"
bitflags = "2.4"
arrayvec = "0.7"
smallstr = "0.3"
smallvec = "1.11"
thiserror = "1.0"