[package]
name = "qubicon_vulkan_internal_macro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.syn]
version = "2.0.47"
default-features = false
features = ["derive"]

[dependencies]
quote = "1.0.35"
proc-macro2 = "1.0.76"