[package]
name = "q_input_server"
version = "0.0.0"
edition = "2021"

[target.'cfg(unix)'.dependencies.nix]
version = "0.27"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.12"
nix = { features = ["fs", "inotify"] }

[dependencies]
arrayvec = "0.7"