[package]
name = "qubicon_short_floats"
version = "0.0.0"
edition = "2021"

[features]
default = ["std"]
std = ["num-traits/std"]

[dependencies.num-traits]
version = "0.2.17"
default-features = false