[package]
name = "qubicon_audio_server"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
arrayvec = "0.7"
bitflags = "2.4"
smallstr = "0.3"
thiserror = "1.0"
num-traits = "0.2"
libpulse-sys = "1.21.0"